version: '3.1'

services:

  mongo:
    image: mongo:4.4.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: greenhurricane
      MONGO_INITDB_ROOT_PASSWORD: mGZKfLHmkknev4ccMR6w
    volumes:
      - ./mongo-data:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: greenhurricane
      ME_CONFIG_MONGODB_ADMINPASSWORD: mGZKfLHmkknev4ccMR6w
      ME_CONFIG_BASICAUTH_USERNAME: greenhurricane
      ME_CONFIG_BASICAUTH_PASSWORD: mGZKfLHmkknev4ccMR6w
      ME_CONFIG_MONGODB_URL: mongodb://greenhurricane:mGZKfLHmkknev4ccMR6w@mongo:27017/

  postgres:
    image: postgres:13.2
    restart: always
    environment:
      POSTGRES_USER: greenhurricane
      POSTGRES_PASSWORD: mGZKfLHmkknev4ccMR6w
      POSTGRES_DB: greenhurricane
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432" 
